import { Button, HorizontalBox, VerticalBox, Slider } from "std-widgets.slint";
import { IconButton } from "@material";

import { Icons } from "assets/icons.slint";
import { DraculaTheme } from "theme/dracula.slint";

import { MusicControl } from "global/music_control.slint";
export { MusicControl }

export component AppWindow inherits Window {
    title: "Sine Music Player";

    preferred-width: 1920px;
    preferred-height: 1080px;
    min-width: 800px;
    min-height: 600px;
    background: DraculaTheme.background;

    VerticalLayout {
        Rectangle {
            // Main area automatically fills remaining vertical space
        }

        Rectangle {
            height: 96px;
            background: DraculaTheme.surface;

            HorizontalBox {
                alignment: space-between;
                padding: 0px;
                // spacing: 24px;

                HorizontalLayout {
                    width: parent.width * 0.2;
                    spacing: 16px;
                    alignment: start;

                    Rectangle {
                        width: self.height;
                        height: parent.height;
                        background: DraculaTheme.muted;
                        clip: true;

                        Image {
                            width: 100%;
                            height: 100%;
                            source: MusicControl.cover-art;
                            image-fit: cover;
                        }
                    }

                    VerticalLayout {
                        alignment: center;
                        spacing: 4px;

                        Text {
                            text: MusicControl.music-title;
                            color: DraculaTheme.foreground;
                            font-size: 16px;
                            font-weight: 600;
                            overflow: elide;
                        }

                        Text {
                            text: MusicControl.music-album-artist;
                            color: DraculaTheme.purple;
                            font-size: 13px;
                            overflow: elide;
                        }
                    }
                }

                VerticalLayout {
                    width: parent.width * 0.5;
                    alignment: center;
                    spacing: 8px;

                    HorizontalLayout {
                        alignment: center;
                        spacing: 16px;

                        IconButton {
                            icon: MusicControl.shuffle-mode ? Icons.shuffle_on : Icons.shuffle_off;
                            clicked => MusicControl.toggle-shuffle();
                        }

                        IconButton {
                            icon: Icons.skip-previous;
                            clicked => MusicControl.previous-button();
                        }

                        IconButton {
                            icon: MusicControl.current-state == "Playing" ? Icons.pause : Icons.play;
                            clicked => MusicControl.toggle-clicked();
                        }

                        IconButton {
                            icon: Icons.skip-next;
                            clicked => MusicControl.next-button();
                        }

                        IconButton {
                            icon: MusicControl.repeat-mode == "Track" ? Icons.repeat_one : MusicControl.repeat-mode == "Playlist" ? Icons.repeat_on : Icons.repeat_off;
                            clicked => MusicControl.toggle-repeat();
                        }
                    }

                    HorizontalLayout {
                        spacing: 12px;
                        alignment: center;

                        Text {
                            text: MusicControl.current-timestamp;
                            color: DraculaTheme.foreground;
                            font-size: 12px;
                            vertical-alignment: center;
                        }

                        Slider {
                            minimum: 0;
                            maximum: MusicControl.music-duration;
                            horizontal-stretch: 1;
                            preferred-width: 600px;
                            value <=> MusicControl.music-progress;

                            changed(value) => MusicControl.set-timestamp(value);
                            released => self.clear-focus();
                        }

                        Text {
                            text: MusicControl.final-timestamp;
                            color: DraculaTheme.foreground;
                            font-size: 12px;
                            vertical-alignment: center;
                        }
                    }
                }

                HorizontalLayout {
                    width: parent.width * 0.2;
                    alignment: end;
                    spacing: 12px;

                    IconButton {
                        icon: Icons.clear;
                        clicked => MusicControl.clear-clicked();
                    }

                    IconButton {
                        icon: Icons.music;
                        clicked => MusicControl.pick-music();
                    }

                    IconButton {
                        icon: Icons.music_folder;
                        clicked => MusicControl.pick-folder();
                    }
                }
            }
        }
    }
}
