export global Icons {
    out property <image> play: @image-url("icons/play.svg");
    out property <image> pause: @image-url("icons/pause.svg");
    out property <image> clear: @image-url("icons/stop.svg");
    out property <image> files: @image-url("icons/files.svg");
    out property <image> fast-forward: @image-url("icons/fast-forward.svg");
    out property <image> fast-rewind: @image-url("icons/fast-rewind.svg");
    out property <image> skip-next: @image-url("icons/skip-next.svg");
    out property <image> skip-previous: @image-url("icons/skip-previous.svg");
    out property <image> repeat_off: @image-url("icons/repeat_off.svg");
    out property <image> repeat_on: @image-url("icons/repeat_on.svg");
    out property <image> repeat_one: @image-url("icons/repeat_one.svg");
    out property <image> shuffle_on: @image-url("icons/shuffle_on.svg");
    out property <image> shuffle_off: @image-url("icons/shuffle_off.svg");
    out property <image> music: @image-url("icons/music.svg");
    out property <image> music_folder: @image-url("icons/music_folder.svg");
}
